[package]
name = "enclone_denovo"
version = "0.5.135"
authors = ["""David Jaffe <david.jaffe@10xgenomics.com>,
              Nigel Delaney <nigel.delaney@10xgenomics.com>,
              Keri Dockter <keri.dockter@10xgenomics.com>,
              Jessica Hamel <jessica.hamel@10xgenomics.com>,
              Lance Hepler <lance.hepler@10xgenomics.com>,
              Shaun Jackman <shaun.jackman@10xgenomics.com>,
              Sreenath Krishnan <sreenath.krishnan@10xgenomics.com>,
              Meryl Lewis <meryl.lewis@10xgenomics.com>,
              Alvin Liang <alvin.liang@10xgenomics.com>,
              Patrick Marks <patrick.marks@10xgenomics.com>,
              Wyatt McDonnell <wyatt.mcdonnell@10xgenomics.com>"""]
edition = "2018"
publish = false

[dependencies]
amino = "0.1"
binary_vec_io = "0.1"
bio = ">=0.35"
debruijn = "0.3"
equiv = "0.1"
fasta_tools = "0.1"
graph_simple = "0.1"
hyperbase = "0.1.2"
io_utils = "0.3"
itertools = "0.10"
kmer_lookup = "0.1.1"
# poa_hmm = { git = "https://github.com/ban-m/partial_order_alignment.git" }
perf_stats = "0.1"
permutation = "0.2"
petgraph = "0.6"
pretty_trace = "0.5"
rayon = "1"
regex = { version = "1", default-features = false, features = ["std", "perf"] }
serde_json = "1"
stats_utils = "0.1"
string_utils = "0.1"
superslice = "1"
tables = "0.1"
vdj_ann = "0.3"
vdj_ann_ref = { git = "https://github.com/10XGenomics/rust-toolbox.git", rev = "277f6d9708b05587a737535fa9869f58edd6bad7" }
vector_utils = "0.1"
