[package]
name = "enclone_versions"
version = "0.5.33"
authors = ["""David Jaffe <david.jaffe@10xgenomics.com>,
              Keri Dockter <keri.dockter@10xgenomics.com>,
              Shaun Jackman <shaun.jackman@10xgenomics.com>,
              Sreenath Krishnan <sreenath.krishnan@10xgenomics.com>,
              Meryl Lewis <meryl.lewis@10xgenomics.com>,
              Patrick Marks <patrick.marks@10xgenomics.com>,
              Wyatt McDonnell <wyatt.mcdonnell@10xgenomics.com>"""]
edition = "2018"
license = "LICENSE.txt"
publish = false

[dependencies]
assert_cmd = "0.12.0"
bio = ">=0.31, <=0.32"
byteorder = "1.3.2"
bytes = ">=0.5.5, <2"
chrono = "0.4.15"
dirs = "2.0.2"
failure = "0.1.6"
flate2 = "1.0.17"
io_utils = "0.2"
itertools = "0.9.0"
ndarray = "0.13"
pager = "0.15.0"
permutation = "0.2.5"
petgraph = "0.4.13"
pretty_trace = "0.3.2"
prost = ">=0.6.1, <0.8"
prost-build = ">=0.6.1, <0.8"
rayon = "1.3"
regex = { version = "1.3.1", default-features = false, features = ["std", "perf"] }
serde = "1.0.90"
serde_derive = "1.0.102"
stats_utils = "0.1.2"
stirling_numbers = "0.1.2"
string_utils = "0.1.1"
tar = "0.4.29"
tilde-expand = "0.1.1"
vector_utils = "0.1.3"


