[package]
name = "enclone_versions"
version = "0.5.64"
authors = ["""David Jaffe <david.jaffe@10xgenomics.com>,
              Nigel Delaney <nigel.delaney@10xgenomics.com>,
              Keri Dockter <keri.dockter@10xgenomics.com>,
              Jessica Hamel <jessica.hamel@10xgenomics.com>,
              Lance Hepler <lance.hepler@10xgenomics.com>,
              Shaun Jackman <shaun.jackman@10xgenomics.com>,
              Sreenath Krishnan <sreenath.krishnan@10xgenomics.com>,
              Meryl Lewis <meryl.lewis@10xgenomics.com>,
              Alvin Liang <alvin.liang@10xgenomics.com>,
              Patrick Marks <patrick.marks@10xgenomics.com>,
              Wyatt McDonnell <wyatt.mcdonnell@10xgenomics.com>"""]
edition = "2018"
license-file = "../LICENSE.txt"
publish = false

[dependencies]
assert_cmd = "1.0.3"
bio = { git = "https://github.com/rust-bio/rust-bio", rev = "9f1452b128fbdbeb54d0823f6da17f40e3cc1575" }
byteorder = "1.4.2"
bytes = ">=0.5.5, <2"
dirs = "3.0.1"
failure = "0.1.6"
flate2 = "1.0.20"
io_utils = "0.2"
itertools = ">= 0.8, <= 0.11"
ndarray = ">= 0.14"
pager = "0.16.0"
permutation = "0.2.5"
petgraph = "0.5"
pretty_trace = "0.5"
prost = { version = ">=0.6.1, <0.8", features = [] }
prost-build = ">=0.6.1, <0.8"
rayon = "1.4"
regex = { version = "1.3.1", default-features = false, features = ["std", "perf"] }
serde = "1.0.90"
serde_derive = "1.0"
stats_utils = "0.1"
stirling_numbers = "0.1.3"
string_utils = "0.1"
tar = "0.4.33"
tilde-expand = "0.1.1"
vector_utils = "0.1.3"


